### ISSUE TITLE
Starting LoRa failed

### ISSUE THREAD

**Issue by MariaDan** [sandeepmistry/arduino-LoRa#352]
I am receiving `Starting LoRa failed` while using the demo code. 
**Hardware** used: Adafruit ItsyBitsy 32u4 - 3V 8MHz and LoRa SX1278 433MHz. 
**Library** used: https://github.com/sandeepmistry/arduino-LoRa
**Connections**: http://www.electronoobs.com/eng_arduino_tut97.php?fbclid=IwAR16EaaTZf3wA0j9nHODxx-9tqBVvVFJPsZ0sz7rHZG99tS_dYMdQxYfTFA
**Arduino IDE Setup**: https://learn.adafruit.com/introducting-itsy-bitsy-32u4/arduino-ide-setup

I verified everything and seems to be fine, I don't understand why I get this error. 
Would you mind helping me, please? 

Thank you so much!

**Comment by IoTThinks** [comment]
No one can do a blind guess with insufficient information.
Likely a pin mapping error to wrong SPI pin.
And wrong SS pin.

**Comment by MariaDan** [comment]
Please tell me what kind of information is missing, so I can give it to you. I left the connections link above, a screenshot from the links above is here: 
![Screenshot_20200328_052104](https://user-images.githubusercontent.com/8324259/77813831-676f6800-70b4-11ea-8f17-820425a61bd7.jpg)

**Comment by IoTThinks** [comment]
Do this to make sure the pins are right.
Of course you need to replace the correct pins to those LORA_...
And make sure you choose the correct board.

And normally Arduino Uno will not have enough current to send LoRa packets far.

99.99% of "Starting LoRa failed" is wrong pin mapping.
```
  SPI.begin(LORA_SCK, LORA_MISO, LORA_MOSI);
  LoRa.setPins(LORA_SS, LORA_RST, LORA_DIO012);
  
  while (!LoRa.begin(433E6)) {
   Serial.println("Starting LoRa failed");
    delay(1000);
  }
```

**Comment by MariaDan** [comment]
Thank you for your answer. 
When I compile, I het this error: **no matching function for call to 'SPIClass::begin(int, int, int)'**
The entire error is here: 
"C:\Users\User\AppData\Local\Temp\arduino_modified_sketch_150590\LoRaSender.ino: In function 'void setup()':

LoRaSender:8:23: error: no matching function for call to 'SPIClass::begin(int, int, int)'

   SPI.begin(13, 12, 11);

                       ^

In file included from C:\Users\User\AppData\Local\Temp\arduino_modified_sketch_150590\LoRaSender.ino:1:0:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\SPI\src/SPI.h:159:15: note: candidate: static void SPIClass::begin()

   static void begin();

               ^~~~~

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.33.0_x86__mdqgnx93n4wtt\hardware\arduino\avr\libraries\SPI\src/SPI.h:159:15: note:   candidate expects 0 arguments, 3 provided

exit status 1
no matching function for call to 'SPIClass::begin(int, int, int)'"

**Comment by IoTThinks** [comment]
My bad,  SPI.begin(LORA_SCK, LORA_MISO, LORA_MOSI); is for arduino-esp32 only.
You can remove the above line for Arduino as the SPI pins are fixed.

**Comment by MariaDan** [comment]
I get the same error. Is is possible to be a problem the fact that I use **Adafruit ItsyBitsy 32u4 - 3V 8MHz** to replace Arduino Uno? 

![12](https://user-images.githubusercontent.com/8324259/77821945-d1a8fc80-70f6-11ea-8809-f866c6c78454.png)

**Comment by IoTThinks** [comment]
Last try.
In setup()
pinMode(LoRa_SS, OUTPUT);
digitalWrite(LoRa_SS, HIGH);

If no luck, then Arduino Uno is a better choice than Arduino Nano.

**Comment by IoTThinks** [comment]
Or you set the SPI frequency down to 8Mhz.
LoRa.setSPIFrequency(8E6);
https://github.com/sandeepmistry/arduino-LoRa/blob/master/API.md#set-spi-frequency

**Comment by MariaDan** [comment]
Unfortunately, it still doesn't work. 
I tried on **Arduino Uno** and it works. What can be the difference? What should I modify on my Itsy Bitsy to make it work as well?

**Comment by IoTThinks** [comment]
I suspect the frequency of your board is too low (8Mhz),

Or your board's pin definition is different from Nano or Uno.

Or the power input of your board is insufficient.
You can try to provide external power to LoRa.

**Comment by MariaDan** [comment]
Thank you so much! You have all my respect. 
I declare this issue closed.

**Comment by MariaDan** [comment]
I found and solved the issue, maybe this answer will help someone: 

1. **Itsy Bitsy has different pinout, so you should make the following connections:** 
    LoRa module -> Itsy Bitsy 
    GND               ->   GND
    Vcc                 ->   3.3V
    MISO             ->   MISO 
    MOSI             ->   MOSI     
    SLCK              ->   SCK
    Nss                ->   D10
    Di00              ->   D7
    RST               ->   D9   

2. **Add the code below in void setup:** 
   LoRa.setSPIFrequency(8E6);  //set the SPI frequency down to 8Mhz
   LoRa.setPins(10, 9, 7); //override the default NSS, NRESET, and DIO0 pins used by the library 

3. **Don't forget to change the frequency, write the one your LoRa module is using**. Mine has 433 MHz:  LoRa.begin(433E6)

**Comment by IoTThinks** [comment]
Love to hear the working update. 

Remember to update the lib to 0.7.2.
0.7.1 has issue.
